### ISSUE TITLE
Ready to chat!

### ISSUE THREAD

**Issue by wwaterman12** [wwaterman12/geo-location-app#1]
I think I am ready to pitch my idea, hope I'm not biting off more than I can chew!

**Comment by amadden80** [comment]
MVP:
- HTML5 Geolocation Determine current user location.
- On a save, the location AND a comment about the location is stored in a database.
- Login: This location is associated with the user.

Bonus:
- When two users have been at the same location... alert the user to find the other user... IRL
- MAYBE a map but... MAYBE
