### ISSUE TITLE
Question RE: https

### ISSUE THREAD

**Issue by wwaterman12** [wwaterman12/geo-location-app#2]
So, Chrome 50 and above only allows Geolocation requests on secure contexts like https.

I'm doing a little research and found free https certificates using something called certbot (https://certbot.eff.org/) 

Is it worth it to try and go down this path and get my app to work on Chrome 50 and above?

**Comment by ddruker** [comment]
Hey Wes,  We haven't really gone into how to setup a server and server side routing just yet which is what you would need to implement this.  It would be a good idea to focus on using the webpack dev server for now.

**Comment by wwaterman12** [comment]
thanks!
